timeout: 5m

run:
  concurrency: 4
  modules-download-mode: readonly
  allow-parallel-runners: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - goimports
    - misspell
    - gocritic
    - gofmt
    - gofumpt
  disable:
    - deadcode
    - varcheck
    - structcheck
    - golint
    - interfacer
    - maligned
    - scopelint

linters-settings:
  goimports:
    local-prefixes: github.com/jlgore/tailpipe-plugin-kubernetes

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - hugeParam

  staticcheck:
    go: "1.24"

  unused:
    go: "1.24"